name: Auto Commit Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Jalan otomatis setiap 5 menit
  workflow_dispatch:      # Tombol manual buat ngetes bot jalan atau nggak

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run script
        run: python bot_commit.py

      - name: Commit and Push
        run: |
          git config --local user.name "amalinars"
          git config --local user.email "keymarlin28@gmail.com"
          git add activity_log.txt
          git commit -m "chore: automatic log update $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin main
